M48
; DRILL file KiCad 10.0.4 date 2026-07-23T05:30:00
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-23T05:30:00-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X60.0Y-71.5
X60.0Y-119.5
X113.0Y-87.0
X128.0Y-101.0
X136.0Y-71.5
X136.0Y-119.5
M30
