/*! \file rx_thresholds.c
 *
 * \brief Receiver detection threshold table. GENERATED by
 * src/apps/pitch_catch_mode_hardware_test/receiver_readout/host/calibrate_thresholds.py
 * on 2026-10-07 - re-run the script rather than editing by hand. See
 * docs/threshold_calibration.md.
 *
 * Source: readouts/parsed (op freq 88521 Hz, ODR 5 -> 15.50 mm/sample
 * one-way, arrival offset +0.44 samples), 450 us TX burst, ringdown cancel 20 samples,
 * 0-5000 mm.
 * Worst-case direct-path |I,Q| (p1), at the measured arrival: 0.52 m 11837, 1.51 m 1295, 3.02 m 540, 3.98 m 223, 4.89 m 188.
 * Level = 0.5 x envelope at the segment's far end / k, k = 1.50 |I,Q| per threshold unit,
 * floor = 2 x noise max (59) / k.
 * Excluded from the fit: none.
 *
 * Replay of this table against the recordings:
 *   0.5m-straight: 50/50 detected, 0 false
 *   1.5m-30deg-tx: 50/50 detected, 0 false
 *   1.5m-45deg-rx: 50/50 detected, 0 false
 *   1.5m-45deg-tx: 50/50 detected, 0 false
 *   1.5m-straight: 50/50 detected, 0 false
 *   3m-30deg-tx: 50/50 detected, 0 false
 *   3m-45deg-rx: 50/50 detected, 0 false
 *   3m-straight: 50/50 detected, 0 false
 *   4m-30deg-rx: 50/50 detected, 0 false
 *   4m-30deg-tx: 50/50 detected, 0 false
 *   4m-straight: 50/50 detected, 0 false
 *   5m-30deg-rx: 50/50 detected, 0 false
 *   5m-30deg-tx: 50/50 detected, 0 false
 *   5m_straight: 50/50 detected, 0 false
 */

#include "sensor_calibration.h"

const ch_thresholds_t sc_rx_thresholds = {
    .threshold = {
        {.start_sample = 0, .level = 4075},
        {.start_sample = 20, .level = 3326},
        {.start_sample = 39, .level = 1785},
        {.start_sample = 57, .level = 958},
        {.start_sample = 75, .level = 514},
        {.start_sample = 93, .level = 275},
        {.start_sample = 148, .level = 147},
        {.start_sample = 209, .level = 78},
    },
};
